### ISSUE TITLE
Warning butchered when images are detected

### ISSUE THREAD

**Issue by jidanni** [mchehab/zbar#116] opened 2020-09-13 02:17 UTC
(Seen in Debian on
```
$ zbarimg --version
0.23.1
```
not sure if still present.)

The words
"Things to check:"
etc. are missing in this case:

```
$ zbarimg /tmp/m.jpg > /dev/null
scanned 1 barcode symbols from 1 images in 0.59 seconds

        . EAN/UPC (EAN-13, EAN-8, EAN-2, EAN-5, UPC-A, UPC-E, ISBN-10, ISBN-13)
        . DataBar, DataBar Expanded
        …
```

Causing it to not make full English sense.

**Comment by jasp00** [comment] 2020-09-13 04:35
Duplicate of #107.

**Closed** 2021-02-15 12:40 UTC
